version: '3.7'

services:
  squid:
    build: squid/
    image: squid-reverse
    env_file: gwproxy.env
      volumes:
         "./logs:/var/log/squid"
    ports:
      - "3128:3128"
    network_mode: host
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1



